### PR TITLE
[NayNay] Signing Fix: Message too long error

### LINKED ISSUE #411: picking validators fails with long strings
i tried to submit a signature request with a long string and was un able to derive an index for subgroup validators

### PR DESCRIPTION
**Pull request by rh0delta**
## Related Issue(s)

- Resolves #411 

## Proposed Changes

- update picking validators to use BigInt instead of regular parseInt

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [x] Manual testing performed

## Screenshots (if applicable)

Screenshot 2024-08-19 at 11 49 04 PM

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code.
- [ ] I have updated documentation, where necessary.

### CODE REVIEW

File: src/signing/index.ts [hunk 1]
```diff
@@ -364,8 +364,14 @@ export default class SignatureRequestManager {
...
       // omg polkadot type gen is a head ache
+      // 
+      // If the Message being signed is too long the sigRequestHash is then converted to a number
+      // so large that the resulting parsed value of parseInt(sigRequest, 16) would return Infinity.
+      // Using BigInt instead solves the Infinity issue, and now allows messages of any length to be
+      // signed.
+      //
       // @ts-ignore: next line
-      const index = parseInt(sigRequest, 16) % keyGroup.unwrap().length
+      const index = Number(BigInt(`0x${sigRequest}`) % BigInt(keyGroup.unwrap().length))
```
Comment (frankiebee) [inline src/signing/index.ts:374]: use the add hex prefix function

**Review by frankiebee — CHANGES_REQUESTED** [review]

**Comment by frankiebee** [comment]
where the tests at?

File: src/signing/index.ts (hunk 1 above)
Comment (frankiebee) [reply src/signing/index.ts:374]: or check first to see if it starts with `0x` before adding it

Comment (frankiebee) [reply src/signing/index.ts:374]: side note:
```
> [0,2,3][1n]
2
``` 
scary 😬

**Comment by rh0delta** [comment]
@frankiebee Ive updated the index calc, and added tests. Ready for re-review!

File: src/signing/index.ts [hunk 2]
```diff
@@ -370,8 +371,12 @@ export default class SignatureRequestManager {
       // Using BigInt instead solves the Infinity issue, and now allows messages of any length to be
       // signed.
       //
+      let sigToConvert = sigRequest
+      if (!hexHasPrefix(sigToConvert)) {
+        sigToConvert = hexAddPrefix(sigRequest)
+      }
```
Comment (mixmix) [inline src/signing/index.ts:377]:
```suggestion
      const sigToConvert = hexAddPrefix(sigRequest)
```

they wrote it so that you don't need to check, it already does
https://github.com/polkadot-js/common/blob/master/packages/util/src/hex/addPrefix.ts

File: src/signing/index.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import { ApiPromise } from '@polkadot/api'
+import { hexHasPrefix, hexAddPrefix } from '@polkadot/util'
```
Comment (mixmix) [inline src/signing/index.ts:2]:
```suggestion
import { hexAddPrefix } from '@polkadot/util'
```

**Review by mixmix — DISMISSED** [review]
Nice test! 
:hot_pepper: Did you check to see that it failed before you applied your fix?

Please merge those suggestions which simplify the code then merge PR.

**Review by frankiebee — APPROVED** [review]
woop woop 👍
